version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
        tty: true
        volumes: 
         - ./app:/usr/src/app
         - /usr/src/app/node_modules
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true 
      volumes: 
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root